--- # autorelease yml file for easybashgui

name: auto release ebg # named it

# Controls when the action will run
on:  # will trigger

  # Build at 00:00 on every 12th day-of-month.
  #schedule:
  #  - cron: "0 0 */12 * *"

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #branches: '**' #'!master' # excludes master
    #paths-ignore: [ '**/README.md' ]
  #pull_request:
    #branches: '**' # matches every branch
    #paths-ignore: [ '**/README.md' ]

    # Triggers the workflow if matching tag is created
    tags: [ 'v*.*' ]

    # only on defined branches
    branches:
      - master # on master branch only
      #- dev # if unncomment will run also on dev branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release-on-push"
  release-on-push: # release if pushed to choosed branches
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # will pull ubuntu image to work with or [ self-hosted ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if some environment variables or permissions are needed
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: # Add all your steps

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Prerequisites
        run: |
          echo "Hello world!"

      - uses: rymndhng/release-on-push-action@master # action used
        with:
          bump_version_scheme: minor # will raise version number [major minor patch no-release]
    
